### ISSUE TITLE
Outdated Apt dependency

### ISSUE THREAD

**Issue by MikeeO** [corey-hammerton/puppet-metricbeat#15]
Hi 

I am busy adding this module to our servers but there is a dependency issue with puppetlabs-apt. 

We are using the latest version of puppetlabs-apt but this module requires >=4.0.0 <5.0.0. 

Is there a chance this can be updated to include the latest puppetlabs-apt (v6.1.1)?

**Comment by flyingstar16** [comment]
The same thing is happening with puppetlabs-stdlib: I can't update any modules because this module requires 

```
"name": "puppetlabs-stdlib",
"version_requirement": ">= 4.13.0 < 5.0.0"
```
but stdlib is now at 5.1.0

Any chance we can get an update for that too?

Thanks
