### ISSUE TITLE
Please push latest version to Puppet Forge

### ISSUE THREAD

**Issue by flyingstar16** [corey-hammerton/puppet-metricbeat#20]
Hi,

the last update on Puppet Forge is from Feb. 2018.

I'm not sure if the push is supposed to happen automatically (if so, it didn't - possibly because the version string hasn't been changed) but the latest changes - the fixes for #7, #10 and #15) - haven't been pushed to Forge, which means they are still causing conflicts to people trying to upgrade.

It would be great if the Forge module could be upgraded too.

Thanks!

**Comment by corey-hammerton** [comment]
#19 is still in development. Once work on it has been completed a new release will be pushed to Puppet Forge.

**Comment by corey-hammerton** [comment]
Version 0.3.0 has been release on Puppet Forge.
