### ISSUE TITLE
Support for Metricbeat version 7

### ISSUE THREAD

**Issue by trenta** [corey-hammerton/puppet-metricbeat#29]

**Comment by sreejithdivakar** [comment]
Hi @trenta 

I had added the below code to my hiera.

metricbeat::major_version: '6'

Then removed the current metricbeat version from my server which is v5. Again pushed the configurations through puppet and it installed the latest version 7.1

metricbeat version 7.1.0 (amd64), libbeat 7.1.0 [03b3db2a1d9d76fdf10475e829fce436c61901e4 built 2019-05-16 00:00:56 +0000 UTC]

Thanks & Regards
Sreejith Divakaran

**Comment by trenta** [comment]
Won't having major_version as 6 mean that the package used is a 6.x package.

From the start of the repo.pp file:
```
class metricbeat::repo inherits metricbeat {
  $apt_repo_url = "https://artifacts.elastic.co/packages/${metricbeat::major_version}.x/apt"
```
