### ISSUE TITLE
Cannot install the module - missing dependencies

### ISSUE THREAD

**Issue by pablogmorales** [corey-hammerton/puppet-metricbeat#5]
Hello Corey.

My modules
/etc/puppetlabs/code/environments/production/modules
├── darin-zypprepo (v1.0.2)
├── eirc-account (v0.2.0)
├── gentoo-portage (v2.3.0)
├── lwf-remote_file (v1.1.3)
├── pcfens-filebeat (v2.1.0)
├── puppet-archive (v1.3.0)
├── puppet-make (v1.1.0)
├── puppet-r10k (v5.0.2)
├── puppetlabs-accounts (v1.1.0)
├── puppetlabs-apache (v1.3.0)
├── puppetlabs-apt (v2.4.0)
├── puppetlabs-concat (v4.0.0)
├── puppetlabs-gcc (v0.3.0)
├── puppetlabs-git (v0.5.0)
├── puppetlabs-inifile (v1.6.0)
├── puppetlabs-powershell (v2.1.2)
├── puppetlabs-ruby (v0.6.0)
├── puppetlabs-stdlib (v4.16.0)
├── puppetlabs-vcsrepo (v1.5.0)
├── rmueller-cron (v0.2.1)
├── saz-ssh (v2.9.1)
├── saz-sudo (v4.1.0)
├── sensu-sensu (v2.2.0)
├── stahnma-epel (v1.3.0)

**puppet module install coreyh-metricbeat --version 0.1.0 --modulepath=/etc/puppetlabs/code/configuration-management/modules --debug**

Debug: Runtime environment: puppet_version=5.3.3, ruby_version=2.4.2, run_mode=user, default_encoding=UTF-8
Notice: Preparing to install into /etc/puppetlabs/code/configuration-management/modules ...
Debug: Could not find translation files for eirc-account at /etc/puppetlabs/code/configuration-management/modules/account/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-accounts at /etc/puppetlabs/code/configuration-management/modules/accounts/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-apache at /etc/puppetlabs/code/configuration-management/modules/apache/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-archive at /etc/puppetlabs/code/configuration-management/modules/archive/locales. Skipping i18n initialization.
Debug: Could not find translation files for rmueller-cron at /etc/puppetlabs/code/configuration-management/modules/cron/locales. Skipping i18n initialization.
Debug: Could not find translation files for stahnma-epel at /etc/puppetlabs/code/configuration-management/modules/epel/locales. Skipping i18n initialization.
Debug: Could not find translation files for pcfens-filebeat at /etc/puppetlabs/code/configuration-management/modules/filebeat/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-gcc at /etc/puppetlabs/code/configuration-management/modules/gcc/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-git at /etc/puppetlabs/code/configuration-management/modules/git/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-inifile at /etc/puppetlabs/code/configuration-management/modules/inifile/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-make at /etc/puppetlabs/code/configuration-management/modules/make/locales. Skipping i18n initialization.
Debug: Could not find translation files for gentoo-portage at /etc/puppetlabs/code/configuration-management/modules/portage/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppet-r10k at /etc/puppetlabs/code/configuration-management/modules/r10k/locales. Skipping i18n initialization.
Debug: Could not find translation files for lwf-remote_file at /etc/puppetlabs/code/configuration-management/modules/remote_file/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-ruby at /etc/puppetlabs/code/configuration-management/modules/ruby/locales. Skipping i18n initialization.
Debug: Could not find translation files for sensu-sensu at /etc/puppetlabs/code/configuration-management/modules/sensu/locales. Skipping i18n initialization.
Debug: Could not find translation files for saz-ssh at /etc/puppetlabs/code/configuration-management/modules/ssh/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-stdlib at /etc/puppetlabs/code/configuration-management/modules/stdlib/locales. Skipping i18n initialization.
Debug: Could not find translation files for saz-sudo at /etc/puppetlabs/code/configuration-management/modules/sudo/locales. Skipping i18n initialization.
Debug: Could not find translation files for puppetlabs-vcsrepo at /etc/puppetlabs/code/configuration-management/modules/vcsrepo/locales. Skipping i18n initialization.
Debug: Could not find translation files for zebrastuff at /etc/puppetlabs/code/configuration-management/modules/zebrastuff/locales. Skipping i18n initialization.
Debug: Could not find translation files for darin-zypprepo at /etc/puppetlabs/code/configuration-management/modules/zypprepo/locales. Skipping i18n initialization.
Notice: Downloading from https://forgeapi.puppet.com ...
Debug: Evicting cache entry for environment 'production'
Debug: Caching environment 'production' (ttl = 0 sec)
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=coreyh-metricbeat&sort_by=version
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&sort_by=version
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&sort_by=version&limit=20&offset=20
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&sort_by=version&limit=20&offset=40
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-apt&sort_by=version
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=puppetlabs-apt&sort_by=version&limit=20&offset=20
Debug: Failed to load library 'pe_license' for feature 'pe_license': cannot load such file -- pe_license
Debug: HTTP GET https://forgeapi.puppet.com/v3/releases?module=darin-zypprepo&sort_by=version
Info: Resolving dependencies ...
Error: Could not install module 'coreyh-metricbeat' (???)
  No version of 'coreyh-metricbeat' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module

puppetserver version: 5.1.4
puppet --version
5.3.3
CentOS Linux release 7.4.1708 (Core)

Any help appreciated
Thanks
Regards

**Comment by corey-hammerton** [comment]
Is your server running behind a firewall? Try `curl` tests to be sure. 
If possible try configuring a proxy to work around this

**Comment by pablogmorales** [comment]
Hi

Im not behind a firewall and not using any proxy, Im connected directly to internet from the AWS instance and was able to install and upgrade other  puppet modules without any issue.

Want me to try something else?

Thanks
Regards

**Comment by pablogmorales** [comment]
What do you want me to try with curl?

**Comment by corey-hammerton** [comment]
Try running `curl https://forgeapi.puppet.com/v3/releases?module=puppetlabs-stdlib&sort_by=version` and post the responses.

Please note I do not manage any PE licenses with this module and is unlikely an issue with the code.

**Comment by pablogmorales** [comment]
Got a long output, these are the last lines

petlabs.com>\n\n* Add stdlib::stages class with a standard set of stages\n",
      "license": "Copyright (C) 2011 Puppet Labs Inc\n\nand some parts:\n\nCopyright (C) 2011 Krzysztof Wilczynski\n\nPuppet Labs can be contacted at: info@puppetlabs.com\n\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n",
      "tasks": [

      ],
      "created_at": "2015-08-12 12:00:13 -0700",
      "updated_at": "2015-08-12 12:00:37 -0700",
      "deleted_at": null,
      "deleted_for": null
    }
  ]
}

**Comment by pablogmorales** [comment]
want  the full output?

**Comment by corey-hammerton** [comment]
No. 

I've also noted that in your environment you have `puppetlabs-apt` installed with version 2.4.0. This module requires at least 4.0.0. Please consider upgrading this or switching to another environment

**Comment by pablogmorales** [comment]
Why is needed apt if Im using CentOS ? can I use --force to install it anyway?

Im also having issues while upgrading apt module

Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'puppetlabs-apt' (v2.4.0 -> latest)
  There are 8 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    Use `puppet module upgrade --force` to upgrade only this module

The only dependency required is puppetlabs-stdlib 4.16.0 < 5.0.0
I have puppetlabs-stdlib (v4.16.0)


Thanks

**Comment by corey-hammerton** [comment]
You can use `--force` to install it. And you answer your question on Debian machines the module is installed the same way which uses the APT package manager, Puppet does not pick and choose which dependency to include at installation time.

Closing this issue since it is not an issue with this module.
